project:
  type: book

bibliography: dxi-skript.bib


crossref:
#   fig-prefix: Abbildung   # (default is "Figure")
#   tbl-prefix: Tabelle    # (default is "Table")
  eq-prefix: Formel # (default is "Equation")
  prp-title: Satz
#   sec-prefix: Abschnitt # (default is "Section")

lang: de
book:
  title: Daten und Information
  subtitle: Data Science Grundlagen für die Life Sciences
  author: 
  - family: Glahn
    given: Christian  
  page-navigation: true
  
  chapters:
  - index.qmd
  # - vorwort.qmd
 
  - kapitel/01-einleitung/kapitel.md
  - kapitel/01-information/kapitel.qmd
  
  - part: Technische Voraussetzungen
    chapters:
    - kapitel/01-tool-chain/tastatur.md
    - kapitel/01-tool-chain/git_github.qmd
    - kapitel/01-tool-chain/project_doc.md

  - part: Datenquellen
    chapters:

    - kapitel/02-daten-sammeln/kapitel.md
    - kapitel/03-daten-organisieren/kapitel.md
    - kapitel/04-dateiformate/kapitel.md
    - kapitel/05-datentypen/kapitel.md
    - kapitel/05-zeichenketten/kapitel.md
    - kapitel/06-datenstrukturen/kapitel.md
    - kapitel/06-daten-kodieren/kapitel.md
    - kapitel/15-externe-datenquellen/kapitel.md
 
  - part: Mathematik der Daten
    chapters:
    - kapitel/06-variablen/kapitel.qmd
    # - kapitel/07-funktionen/kapitel.md
    # - kapitel/07-neutrales-element/kapitel.md
    - kapitel/08-boolsche-operationen/kapitel.qmd
    - kapitel/09-vektor-operationen/kapitel.md
    - kapitel/10-matrix-operationen/kapitel.md
    - kapitel/11-indizieren-gruppieren/kapitel.md
    - kapitel/12-daten-formen/kapitel.md

  - part: Deskriptive Datenanalyse
    chapters:
    
    - kapitel/13-daten-beschreiben/kapitel.md
    - kapitel/14-daten-visualisieren/kapitel.md
    - kapitel/10-lineare-modelle/kapitel.md


format:
  html:
    theme: bootstrap
    toc: true
    html-math-method: katex

csl: _contrib/apa.csl