project:
  type: book

book:
  title: Prinzipien der Datenorganisation
  author: 
  - family: Glahn
    given: Christian  
  page-navigation: true

  chapters:
  - index.qmd
  # - vorwort.qmd
 
  - kapitel/einleitung/kapitel.md
  - kapitel/information/kapitel.md
  - kapitel/tool-chain/kapitel.md

  - part: "Teil I: Datenquellen"
    chapters:
    - kapitel/daten-sammeln/kapitel.md
    - kapitel/daten-organisieren/kapitel.md
    - kapitel/dateiformate/kapitel.md
    - kapitel/datentypen/kapitel.md
    - kapitel/zeichenketten/kapitel.md
    - kapitel/datenstrukturen/kapitel.md
    - kapitel/externe-datenquellen/kapitel.md
 
  - part: "Teil II: Mathematik der Daten"
    chapters:
    - kapitel/variablen/kapitel.md
    - kapitel/neutrales-element/kapitel.md
    - kapitel/funktionen/kapitel.md
    - kapitel/vektor-operationen/kapitel.md
    - kapitel/boolsche-operationen/kapitel.md
    - kapitel/matrix-operationen/kapitel.md
  
  - part: "Teil III: Deskriptive Datenanalyse"
    chapters:
    - kapitel/daten-formen/kapitel.md
    - kapitel/daten-beschreiben/kapitel.md
    - kapitel/daten-visualisieren/kapitel.md
    - kapitel/lineare-modelle/kapitel.md

format:
  html:
    theme: bootstrap
    toc: true
    html-math-method: katex

csl: _contrib/apa.csl